name: MLProject CI

on:
  push:
    paths:
      - 'MLProject/**'
      - '.workflow/**'
      - 'Tautan_Docker_Hub.txt'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pandas scikit-learn mlflow
      - name: Run MLProject
        run: |
          cd MLProject
          python modelling.py
      - name: Upload model artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns
